### ISSUE TITLE
TypeError: Value of "this" must be of type URLSearchParams

### ISSUE THREAD

**Issue by Hennard** [andrescheca/hands-on-hacking#1]
Hi,

Hands-on-hacking giving "Internal Server Error" on the webpage.

Remix App Server started at http://localhost:3000 (http://192.168.106.133:3000)
GET / 500 148 - 1.982 ms
TypeError: Value of "this" must be of type URLSearchParams

npm -v: 10.2.4
node -v:  v21.5.0
docker -v: Docker version 24.0.7, build afdd53b

Regards.

**Comment by Hennard** [comment]
Fix:
$ npm install -g n
$ n 18.18.0

**Comment by andrescheca** [comment]
Thanks @Hennard  for this, I updated the README file to indicate the the last working version of NodeJS is 18.18.0
